### ISSUE TITLE
Themes not appearing

### ISSUE THREAD

**Issue by jononomo** [rvagg/morkdown#30]
I just installed `node` on my macbook using `Homebrew`.  The first node program I installed was `morkdown`.  I did:

    > npm install -g morkdown

I now have `which morkdown` returning `/usr/local/bin/morkdown` which is a symbolic link pointing to `/usr/local/lib/node_modules/morkdown/bin/morkdown.js`, which is executable.

However, when I launch morkdown via:

    > morkdown great_american_novel.md

I get the chrome app launched and the input and output accepting plain text and generating HTML properly, but I get no CSS themes and everything is just blank black-on-white with no styling whatsoever.

When I look at the javascript console I see output like the following:

    > Failed to load resource: the server responded with a status of 404 (Not Found)  http://localhost:2846/codemirror/theme/monokai.css

**Comment by rvagg** [comment]
@jononomo does `/usr/local/lib/node_modules/morkdown/static/codemirror/theme/monokai.css` exist? and when you're running the app can you see if http://localhost:2846/codemirror/theme/monokai.css loads in a normal browser window?

Also, what version of node are you using? `node -v` from the commandline will tell you.

**Comment by jononomo** [comment]
Here are some results from my command line:

    > node -v
    v0.10.35

Checking if CSS file exists:

    > cat /usr/local/lib/node_modules/morkdown/static/codemirror/monokai.css
    /* Based on Sublime Text's Monokai theme */
    
    .cm-s-monokai.CodeMirror {background: #272822; color: #f8f8f2;}
    .cm-s-monokai div.CodeMirror-selected {background: #49483E !important;}
    .cm-s-monokai .CodeMirror-gutters {background: #272822; border-right: 0px;}
    .cm-s-monokai .CodeMirror-guttermarker { color: white; }
    ETC...

Checking if `http://localhost:PORT/codemirror/theme/monokai.css` loads in a normal browser window...
 
No.  It does not.

**Comment by jononomo** [comment]
Looks like the theme files are being referred to correctly in `index.html`:

    > head index.html
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Morkdown [{file}]</title>
        <link rel="stylesheet" href="/codemirror/codemirror.css">
        <link rel="stylesheet" href="/codemirror/theme/monokai.css">
        <link rel="stylesheet" href="/codemirror/theme/ambiance.css">
        <link rel="stylesheet" href="/codemirror/theme/cobalt.css">
        <link rel="stylesheet" href="/codemirror/theme/erlang-dark.css">

should be like:

        <link rel="stylesheet" href="/codemirror/monokai.css">

whithout the `theme` directory.

**Comment by rvagg** [comment]
odd, this could be something to do with the install process for these files so I've modified it to be more explicit in fe7e6103dde and published a new release. @jononomo run `npm install -g morkdown` and you should get 2.4.2 with a new install script. Let us know how you go with that.

**Comment by jononomo** [comment]
Yes, it works now.  Unfortunately the theme's seem to fail when they meet fenced code blocks.
