### ISSUE TITLE
I'd like to only create the morkdown process.

### ISSUE THREAD

**Issue by iasj** [rvagg/morkdown#33]
Hi. 

I'm using morkdown (good stuff by the way), and I use it in the following scenario:

Every day, I bring my laptop to work. I access this laptop via ssh, so I can manage my projects within a tmux session (laptop is the server). Hence, every time I want to use morkdown, I have to open my laptop, start morkdown with some markdown file, and I take a note of the port that is created. Then I close the laptop, and come back to the client computer, open the broser and go to:

-> http://10.7.5.48:some_random_port

where 10.7.5.48 is my local IP address. 

So, I like to know how to only create the process, take the corresponding port created, and I'd like to do this inside Tmux. I think that a daemon would be nice. I mean, would be great if the server could accept control messages after started. It is good for scripts. Is there anything like that implemented already?

I found no "--help" flag.

**Comment by rvagg** [comment]
do an `npm install morkdown` and use it as a library, something like this would work:

```
$ node -e '
var Morkdown = require(".");
var md = Morkdown("/tmp/foo.md").listen(function (err) {
  if (err) throw err;
  console.log("http://localhost:" + this.address().port)
})'
```

Or you can write that into a main.js file to do something more permanent. Note that the filename is fixed, one server per filename. The `listen()` call is basically the same as `httpServer.listen()` so you can pass arguments to it like `listen(0, 'localhost', function (err) { ... })` if you want to be specific (`0` here being a random port but you could specify one). Then just point your browser at the address/port it's listening on. It's designed for Chrome only but may work in other browsers.

**Comment by iasj** [comment]
It worked very well after I change require(".") to require("morkdown"). I have morkdown installed globally, so I think it is because of that. 
I've tested to set a specific IP address and port as well. It's perfect, just what I was needing!

Thanks a lot!

**Comment by rvagg** [comment]
yeah, sorry, `require('morkdown')` is what I should have written, I used `'.'` when testing that out in the morkdown directory!
