### ISSUE TITLE
can't run from within a tmux session

### ISSUE THREAD

**Issue by chesles** [rvagg/morkdown#4]
I don't if this is something you can fix, but when I run `morkdown` from within tmux (on OS X Mountain Lion), I get either the "Oh Snap" page or a blank white page, and nothing renders. This output is logged to the terminal:

> **2013-05-21 20:51:05.416** Google Chrome Helper[66210:707] *** CFMessagePort: bootstrap_register(): failed 1099 (0x44b) 'unknown error code', port = 0x5203, name = 'com.apple.tsm.portname'
> See /usr/include/servers/bootstrap_defs.h for the error codes.
> **2013-05-21 20:51:06.926** Google Chrome Helper[66210:707] Could not rendezvous with font server (error 268435459)
> **2013-05-21 20:51:06.926** Google Chrome Helper[66210:707] XType: unable to make a connection to the font daemon!
> **2013-05-21 20:51:06.926** Google Chrome Helper[66210:707] registering /System/Library/Fonts/*, /System/Library/Fonts/Base/*, and /Library/Fonts/* locally

This ChromeDriver bug report seems to be related: https://code.google.com/p/chromedriver/issues/detail?id=52

**Comment by leesei** [comment]
Should this issue be closed then?

**Comment by rvagg** [comment]
probably, thanks @leesei
